language: go

go:
  - 1.6
  - 1.7

install:
  - go get github.com/golang/lint/golint
  - go get github.com/atotto/clipboard
  - go get github.com/peterhellberg/giphy

before_script:
  - go vet
  - golint
